// GENERATED by src/build/generate-hero-animations.js — do not hand-edit.
// Source of truth is animation/json/grid-*.json.

export const HERO_ANIMATIONS = [
	"about",
	"bomb",
	"content",
	"paid",
	"seo",
	"websites"
];

export const DEFAULT_HERO_ANIMATION = "bomb";
