<?php
/**
 * GENERATED by src/build/generate-hero-animations.js — do not hand-edit.
 *
 * Source of truth is animation/json/grid-*.json. Read through
 * cb_chillibyte_2026_get_hero_animation_config() rather than requiring this
 * file directly.
 *
 * @package cb-chillibyte-2026
 */

defined( 'ABSPATH' ) || exit;

return array(
	'available' => array(
		'about',
		'bomb',
		'content',
		'paid',
		'seo',
		'websites',
	),
	'default'   => 'bomb',
);
